# Use the official PyTorch image as a parent image
FROM pytorch/pytorch:latest

# Set the working directory
WORKDIR /app

# Copy the rest of your application's code
COPY . /app

# Command to run on container start
CMD ["python"]